# Generated by Django 4.2.14 on 2024-10-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
    ]
