# Generated by Django 4.2.14 on 2024-11-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic'},
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
